# Generated by Django 4.2.2 on 2023-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("pwd", models.CharField(max_length=30)),
                ("pwd_question", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prize_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("description", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_id", models.CharField(max_length=30)),
                ("seller_name", models.CharField(max_length=30)),
                ("seller_last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("pwd", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=30)),
                ("cost", models.IntegerField()),
                ("available", models.BooleanField()),
            ],
        ),
    ]
