# Generated by Django 4.2.2 on 2023-06-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SorteoTique", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="pwd",),
        migrations.RemoveField(model_name="client", name="pwd_question",),
        migrations.RemoveField(model_name="seller", name="pwd",),
    ]
